# Generated by Django 3.2.4 on 2022-01-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211231_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecontact',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
